name: Publish Maven

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - uses: burrunan/gradle-cache-action@v1
        name: Cache gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: publish maven
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USER_NAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASS_WORD }}
          SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY}}
          SIGNING_KEY_ID: ${{ secrets.GPG_SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASS_WORD }}
        run: ./gradlew publish -PSONATYPE_AUTOMATIC_RELEASE=true -PmavenCentralUsername=$MAVEN_USERNAME -PmavenCentralPassword=$MAVEN_PASSWORD -PsigningInMemoryKeyId=$SIGNING_KEY_ID -PsigningInMemoryKeyPassword=$SIGNING_PASSWORD -PsigningInMemoryKey=$SIGNING_KEY
